# Generated by Django 2.1.1 on 2018-10-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robotkiller',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=16)),
                ('visits', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'robotkiller',
            },
        ),
    ]
